import {useEffect,useState} from "react";
import {apiGet,apiPatch} from "../api";
import PageHeader from "../components/PageHeader";
const P=[["can_view_dashboard","View Dashboard"],["can_view_parts","View Parts"],["can_edit_parts","Edit Parts"],["can_receive_stock","Receive Stock"],["can_issue_stock","Issue Stock"],["can_view_suppliers","View Suppliers"],["can_view_machines","View Machines"],["can_manage_roles","Manage Roles"]];
export default function RoleSettings(){const[roles,setRoles]=useState([]),[employees,setEmployees]=useState([]),[msg,setMsg]=useState(""),[err,setErr]=useState("");
async function load(){try{const[r,e]=await Promise.all([apiGet("/roles/"),apiGet("/employees/")]);setRoles(r.results||[]);setEmployees(e.results||[])}catch(x){setErr(x.message)}}useEffect(()=>{load()},[]);
function toggle(id,k,v){setRoles(xs=>xs.map(r=>r.id===id?{...r,permissions:{...r.permissions,[k]:v}}:r))}
async function save(r){try{await apiPatch(`/roles/${r.id}/`,{permissions:r.permissions});setMsg(`บันทึก ${r.role_name} แล้ว`)}catch(x){setErr(x.message)}}
async function assign(e,role){try{await apiPatch(`/employees/${e.id}/role/`,{role});setMsg(`เปลี่ยน Role ของ ${e.name} แล้ว`);load()}catch(x){setErr(x.message)}}
return <><PageHeader title="Role & Permissions" subtitle="กำหนดสิทธิ์และ Role ของพนักงาน"/>{msg&&<div className="pf-success">{msg}</div>}{err&&<div className="pf-login-error">{err}</div>}<section className="panel"><div className="pf-role-grid">{roles.map(r=><div className="pf-role-card" key={r.id}><h3>{r.display_name||r.role_name}</h3>{P.map(([k,l])=><label className="pf-permission" key={k}><span>{l}</span><input type="checkbox" checked={!!r.permissions[k]} onChange={e=>toggle(r.id,k,e.target.checked)}/></label>)}<button onClick={()=>save(r)}>Save permissions</button></div>)}</div></section><section className="panel"><h2>Employees</h2><div className="table-wrap"><table><thead><tr><th>ID</th><th>Name</th><th>Department</th><th>Role</th></tr></thead><tbody>{employees.map(e=><tr key={e.id}><td>{e.employee_code}</td><td>{e.name}</td><td>{e.department||"-"}</td><td><select value={e.role||""} onChange={x=>assign(e,x.target.value)}><option value="" disabled>Select role</option>{roles.filter(r=>r.active).map(r=><option key={r.id} value={r.role_name}>{r.display_name||r.role_name}</option>)}</select></td></tr>)}</tbody></table></div></section></>}
