import { useEffect, useMemo, useState } from "react";
import { apiGet } from "../api";
import { Alert, fmt } from "../components/Common";
import { MobileEmpty, MobileLoading, MobilePage, MobileSearch } from "./MobileCommon";
export default function MobileHistory(){
 const[rows,setRows]=useState([]),[q,setQ]=useState(""),[type,setType]=useState("ALL"),[loading,setLoading]=useState(true),[error,setError]=useState("");
 async function load(force=false){setLoading(true);setError("");try{const p=new URLSearchParams({type,q:"",requester_id:"",recorder_id:""});const d=await apiGet(`/history/?${p}`,{forceRefresh:force});setRows(d.results||[])}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[type]); const shown=useMemo(()=>rows.filter(x=>!q||`${x.item_id} ${x.part_name} ${x.part_detail} ${x.machine} ${x.requester} ${x.recorder}`.toLowerCase().includes(q.toLowerCase())),[rows,q]);
 return <MobilePage title="History" subtitle="ประวัติการเคลื่อนไหว Stock" actions={<button className="m-icon-action" onClick={()=>load(true)}>↻</button>}><Alert>{error}</Alert><div className="m-segment wide"><button className={type==="ALL"?"active":""} onClick={()=>setType("ALL")}>ทั้งหมด</button><button className={type==="ISSUE"?"active":""} onClick={()=>setType("ISSUE")}>เบิก</button><button className={type==="RECEIVE"?"active":""} onClick={()=>setType("RECEIVE")}>รับเข้า</button><button className={type==="ADJUST"?"active":""} onClick={()=>setType("ADJUST")}>ปรับยอด</button></div><MobileSearch value={q} onChange={setQ} placeholder="ค้นหา Item / Part / Machine / คน..."/>{loading?<MobileLoading/>:shown.length===0?<MobileEmpty/>:<div className="m-card-list">{shown.map(r=><article className="m-history-card" key={r.id}><div className="m-row-between"><div><b>{r.item_id}</b><h3>{r.part_name}</h3></div><span className={`m-tx ${String(r.tx_type||r.type||"").toLowerCase()}`}>{r.tx_type||r.type}</span></div><p>{r.part_detail||"-"}</p><div className="m-history-qty"><span>จำนวน</span><strong>{fmt(r.quantity)} {r.unit||r.unit_code||""}</strong></div><div className="m-info-grid"><span>Machine<b>{r.machine||"-"}</b></span><span>ผู้เบิก<b>{r.requester||"-"}</b></span><span>ผู้บันทึก<b>{r.recorder||"-"}</b></span><span>เวลา<b>{r.created_at_display||r.created_at||"-"}</b></span></div>{r.remark&&<div className="m-note">{r.remark}</div>}</article>)}</div>}</MobilePage>
}
