import { useEffect, useMemo, useState } from "react";
import { apiGet, apiPost } from "../api";
import { useAuth } from "../auth";
import { Alert, fmt, money } from "../components/Common";
import { MobileEmpty, MobileLoading, MobilePage, MobileSearch } from "./MobileCommon";

function lifeLabel(x){if(x.lifecycle_status==="WAIT_CONFIRM")return "Wait Confirm";if(x.lifecycle_status==="CANCELLED")return "Cancelled";if(x.lifecycle_status==="COMPLETED")return "Completed";return x.status||"Active"}
export default function MobileOrders(){const auth=useAuth();const[rows,setRows]=useState([]),[kpi,setKpi]=useState({}),[q,setQ]=useState(""),[status,setStatus]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState(""),[busy,setBusy]=useState("");async function load(force=false){setLoading(true);setError("");try{const p=new URLSearchParams({view:"normal",q:"",urgency:"all",job:"",status});const d=await apiGet(`/orders/?${p}`,{forceRefresh:force});setRows(d.results||[]);setKpi(d.kpi||{})}catch(e){setError(e.message)}finally{setLoading(false)}}useEffect(()=>{load()},[status]);const shown=useMemo(()=>rows.filter(x=>!q||`${x.order_number} ${x.item_id} ${x.part_name} ${x.machine_name} ${x.machine_code} ${x.vendor_name} ${x.po_number}`.toLowerCase().includes(q.toLowerCase())),[rows,q]);async function act(row,action){if(busy)return;let ok=true,reason="";if(action==="receive")ok=confirm(`ยืนยันรับ ${row.order_number}?`);if(action==="wait")ok=confirm(`เปลี่ยน ${row.order_number} เป็น Wait Confirm?`);if(action==="cancelwait")ok=confirm(`ยกเลิก Wait Confirm ${row.order_number}?`);if(action==="cancel"){ok=confirm(`ยกเลิก ${row.order_number}?`);if(ok)reason=prompt("เหตุผลการยกเลิก","")||""}if(!ok)return;setBusy(row.id+action);try{if(action==="receive")await apiPost(`/orders/${row.id}/receive/`,{});if(action==="wait")await apiPost(`/orders/${row.id}/wait-confirm/`,{wait_confirm:true});if(action==="cancelwait")await apiPost(`/orders/${row.id}/wait-confirm/`,{wait_confirm:false});if(action==="cancel")await apiPost(`/orders/${row.id}/cancel/`,{cancel:true,reason});await load(true)}catch(e){setError(e.message)}finally{setBusy("")}}
return <MobilePage title="Order" subtitle="ติดตามและจัดการ Order บนมือถือ" actions={<button className="m-icon-action" onClick={()=>load(true)}>↻</button>}><Alert>{error}</Alert><div className="m-kpi-row"><div><span>ทั้งหมด</span><b>{fmt(kpi.total||rows.length)}</b></div><div className="warning"><span>Wait</span><b>{fmt(kpi.wait_confirm||0)}</b></div><div className="success"><span>Complete</span><b>{fmt(kpi.complete||kpi.completed||0)}</b></div></div><MobileSearch value={q} onChange={setQ} placeholder="Order / Item / Part / Machine / PO..."/><select className="m-full-select" value={status} onChange={e=>setStatus(e.target.value)}><option value="">ทุกสถานะ</option><option>New Order</option><option>Wait Quotation</option><option>Wait Issue P/R</option><option>Wait for Item</option><option>Complete Order</option></select>{loading?<MobileLoading/>:shown.length===0?<MobileEmpty/>:<div className="m-card-list">{shown.map(o=><article className="m-order-card" key={o.id}><div className="m-row-between"><div><b>{o.order_number}</b><small>{o.order_date||""}</small></div><span className={`m-order-life ${String(o.lifecycle_status||o.status).toLowerCase().replaceAll("_","-")}`}>{lifeLabel(o)}</span></div><div className="m-order-item"><b>{o.item_id||"-"}</b><h3>{o.part_name||"-"}</h3><p>{o.detail||o.part_detail||"-"}</p></div><div className="m-info-grid"><span>จำนวน<b>{fmt(o.amount)} {o.unit_text||o.unit||""}</b></span><span>Machine<b>{o.machine_code||o.machine_name||"-"}</b></span><span>PO<b>{o.po||o.po_number||"-"}</b></span><span>Vendor<b>{o.vendor_name||o.vendor||"-"}</b></span></div>{o.price&&<div className="m-order-value">฿ {money(Number(o.price||0)*Number(o.amount||0))}</div>}<div className="m-order-actions">{["ACTIVE","WAIT_CONFIRM"].includes(o.lifecycle_status)&&(auth.can("can_edit_purchase_info")||auth.can("can_receive_order")||auth.can("can_cancel_order"))&&<>{o.lifecycle_status==="ACTIVE"?(auth.can("can_edit_purchase_info")&&<button onClick={()=>act(o,"wait")} disabled={!!busy}>Wait Confirm</button>):(auth.can("can_edit_purchase_info")&&<button onClick={()=>act(o,"cancelwait")} disabled={!!busy}>ยกเลิก Wait</button>)}{auth.can("can_receive_order")&&<button className="receive" onClick={()=>act(o,"receive")} disabled={!!busy}>รับของ</button>}{auth.can("can_cancel_order")&&<button className="danger" onClick={()=>act(o,"cancel")} disabled={!!busy}>ยกเลิก</button>}</>}</div></article>)}</div>}</MobilePage>}
