import { useEffect, useMemo, useState } from "react";
import { apiDelete, apiGet, apiPatch } from "../api";
import { useAuth } from "../auth";
import { Alert, Modal, PageHeader, fmt } from "../components/Common";

const MONTHS_TH = ["มกราคม","กุมภาพันธ์","มีนาคม","เมษายน","พฤษภาคม","มิถุนายน","กรกฎาคม","สิงหาคม","กันยายน","ตุลาคม","พฤศจิกายน","ธันวาคม"];

export function EditHistory({ row, options, onClose, onSaved }) {
  const [quantity, setQuantity] = useState(row.quantity);
  const [machineId, setMachineId] = useState(row.machine ? (options.machines||[]).find(x=>x.code===row.machine)?.id||"" : "");
  const [requesterId, setRequesterId] = useState(row.requester_id||"");
  const [recorderId, setRecorderId] = useState(row.recorder_id||"");
  const [remark, setRemark] = useState(row.remark||"");
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  async function save(e){e.preventDefault();setBusy(true);setError("");try{await apiPatch(`/history/${row.id}/`,{quantity,machine_id:machineId,requester_id:requesterId,recorder_id:recorderId,remark});onSaved();}catch(err){setError(err.message)}finally{setBusy(false)}}
  return <Modal title="แก้ไขข้อมูล History" onClose={onClose}><form onSubmit={save}><div className="form-grid"><label className="field"><span>จำนวน *</span><input type="number" min="0.0001" step="any" value={quantity} onChange={e=>setQuantity(e.target.value)} required/></label><label className="field"><span>เครื่องจักร</span><select value={machineId} onChange={e=>setMachineId(e.target.value)}><option value="">-</option>{(options.machines||[]).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="field"><span>ผู้เบิก</span><select value={requesterId} onChange={e=>setRequesterId(e.target.value)}><option value="">-</option>{(options.employees||[]).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="field"><span>ผู้บันทึก</span><select value={recorderId} onChange={e=>setRecorderId(e.target.value)}><option value="">-</option>{(options.employees||[]).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="field span2"><span>Remark</span><textarea rows="3" value={remark} onChange={e=>setRemark(e.target.value)}/></label></div><Alert>{error}</Alert><div className="modal-actions"><button type="button" className="btn ghost" onClick={onClose}>ยกเลิก</button><button className="btn primary" disabled={busy}>บันทึก</button></div></form></Modal>
}

function HistoryTable({ rows, auth, onEdit, onDelete }) {
  return <div className="history-table-wrap"><table className="history-table"><colgroup><col className="hc-date"/><col className="hc-type"/><col className="hc-item"/><col className="hc-name"/><col className="hc-detail"/><col className="hc-maker"/><col className="hc-location"/><col className="hc-machine"/><col className="hc-requester"/><col className="hc-recorder"/><col className="hc-qty"/><col className="hc-unit"/><col className="hc-action"/></colgroup><thead><tr><th>วัน / เวลา</th><th>ประเภท</th><th>Item ID</th><th>Part Name</th><th>Part Detail</th><th>Maker</th><th>Location</th><th>เครื่องจักร</th><th>ผู้เบิก</th><th>ผู้บันทึก</th><th>จำนวน</th><th>Unit</th><th>Action</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><b>{r.date}</b><small>{r.time}</small></td><td><span className={`status ${r.type==="IN"?"success":r.type==="OUT"?"danger":"warning"}`}>{r.type==="IN"?"รับเข้า":r.type==="OUT"?"เบิกออก":"ปรับยอด"}</span></td><td><b>{r.item_id}</b></td><td className="history-part-name">{r.part_name}</td><td className="history-detail">{r.part_detail||"-"}</td><td>{r.maker||"-"}</td><td>{r.location||"-"}</td><td>{r.type==="OUT"?r.machine||"-":"-"}</td><td>{r.type==="OUT"?r.requester||"-":"-"}</td><td>{r.recorder||"-"}</td><td><b>{fmt(r.quantity)}</b></td><td>{r.unit}</td><td><div className="history-actions">{auth.can("can_edit_history")&&<button className="mini" onClick={()=>onEdit(r)}>แก้ไข</button>}{auth.can("can_delete_history")&&<button className="mini danger" onClick={()=>onDelete(r)}>ลบ</button>}</div></td></tr>)}</tbody></table></div>
}

export default function History(){
  const auth=useAuth();
  const [rows,setRows]=useState([]); const [options,setOptions]=useState({}); const [type,setType]=useState("ALL"); const [q,setQ]=useState(""); const [requester,setRequester]=useState(""); const [recorder,setRecorder]=useState(""); const [error,setError]=useState(""); const [edit,setEdit]=useState(null); const [loading,setLoading]=useState(true);
  const [openYears,setOpenYears]=useState({}); const [openMonths,setOpenMonths]=useState({});
  async function load(){setLoading(true);setError("");try{const params=new URLSearchParams({type,q,requester_id:requester,recorder_id:recorder});const [h,o]=await Promise.all([apiGet(`/history/?${params}`),apiGet("/options/")]);setRows(h.results||[]);setOptions(o||{});}catch(err){setError(err.message)}finally{setLoading(false)}}
  useEffect(()=>{load()},[type,requester,recorder]);
  const shown=useMemo(()=>rows.filter(x=>!q||`${x.item_id} ${x.part_name} ${x.part_detail} ${x.maker} ${x.machine} ${x.requester} ${x.recorder}`.toLowerCase().includes(q.toLowerCase())),[rows,q]);
  const groups=useMemo(()=>{const years=new Map();for(const row of shown){const d=new Date(row.transaction_date);const valid=!Number.isNaN(d.getTime());const year=valid?String(d.getFullYear()):String(row.date||"").slice(-4);const monthIndex=valid?d.getMonth():0;const monthKey=`${year}-${String(monthIndex+1).padStart(2,"0")}`;if(!years.has(year))years.set(year,new Map());const months=years.get(year);if(!months.has(monthKey))months.set(monthKey,{key:monthKey,label:MONTHS_TH[monthIndex]||monthKey,rows:[]});months.get(monthKey).rows.push(row)}return Array.from(years.entries()).sort((a,b)=>Number(b[0])-Number(a[0])).map(([year,months])=>({year,months:Array.from(months.values()).sort((a,b)=>b.key.localeCompare(a.key))}))},[shown]);
  useEffect(()=>{if(!groups.length)return;const y=groups[0];const m=y.months[0];setOpenYears(prev=>Object.keys(prev).length?prev:{[y.year]:true});if(m)setOpenMonths(prev=>Object.keys(prev).length?prev:{[m.key]:true})},[groups]);
  async function remove(row){if(!window.confirm(`ยืนยันลบ/ยกเลิกรายการ ${row.item_id} ?\nระบบจะเก็บ Audit Log ไว้`))return;try{await apiDelete(`/history/${row.id}/delete/`);load()}catch(err){setError(err.message)}}
  return <><PageHeader title="ประวัติการเบิก / รับเข้า (History)" subtitle="จัดกลุ่มตามปีและเดือน · Stock IN / OUT / Adjustment"/><Alert>{error}</Alert><section className="panel"><div className="tab-row history-tabs"><button className={`tab ${type==="ALL"?"active":""}`} onClick={()=>setType("ALL")}>ทั้งหมด</button><button className={`tab ${type==="IN"?"active":""}`} onClick={()=>setType("IN")}>รับเข้า</button><button className={`tab ${type==="OUT"?"active":""}`} onClick={()=>setType("OUT")}>เบิกออก</button><button className={`tab ${type==="ADJUSTMENT"?"active":""}`} onClick={()=>setType("ADJUSTMENT")}>ปรับยอด</button></div><div className="toolbar wrap"><input className="search-input" value={q} onChange={e=>setQ(e.target.value)} placeholder="ค้นหา Item ID / Part / Machine..."/><select value={requester} onChange={e=>setRequester(e.target.value)}><option value="">ผู้เบิกทั้งหมด</option>{(options.employees||[]).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select value={recorder} onChange={e=>setRecorder(e.target.value)}><option value="">ผู้บันทึกทั้งหมด</option>{(options.employees||[]).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><button className="btn ghost" onClick={load}>ค้นหา</button></div>{loading?<div className="empty">กำลังโหลด...</div>:groups.length===0?<div className="empty">ไม่พบข้อมูล</div>:<div className="history-groups">{groups.map(y=><section className="history-year" key={y.year}><button className="history-collapse year" onClick={()=>setOpenYears(x=>({...x,[y.year]:!x[y.year]}))}><span>{openYears[y.year]?"▾":"▸"} ปี {y.year}</span><b>{y.months.reduce((n,m)=>n+m.rows.length,0)} รายการ</b></button>{openYears[y.year]&&<div className="history-months">{y.months.map(m=><section className="history-month" key={m.key}><button className="history-collapse month" onClick={()=>setOpenMonths(x=>({...x,[m.key]:!x[m.key]}))}><span>{openMonths[m.key]?"▾":"▸"} {m.label}</span><b>{m.rows.length} รายการ</b></button>{openMonths[m.key]&&<HistoryTable rows={m.rows} auth={auth} onEdit={setEdit} onDelete={remove}/>}</section>)}</div>}</section>)}</div>}</section>{edit&&<EditHistory row={edit} options={options} onClose={()=>setEdit(null)} onSaved={()=>{setEdit(null);load()}}/>}</>
}
