import { useEffect, useMemo, useState } from "react";
import { apiDelete, apiGet, apiPatch, apiPost } from "../api";
import { useAuth } from "../auth";
import { Alert, Modal, PageHeader } from "../components/Common";

export function VendorModal({ row, onClose, onSaved }) {
  const [form,setForm]=useState(row||{code:"",name:"",contact:"",phone:"",email:"",lead_time_days:0,remark:"",active:true});
  const [error,setError]=useState(""); const [busy,setBusy]=useState(false); const set=(k,v)=>setForm(x=>({...x,[k]:v}));
  async function save(e){e.preventDefault();setBusy(true);setError("");try{row?await apiPatch(`/suppliers/${row.id}/`,form):await apiPost("/suppliers/",form);onSaved()}catch(err){setError(err.message)}finally{setBusy(false)}}
  return <Modal title={row?"แก้ไข Vendor":"เพิ่ม Vendor"} onClose={onClose}><form onSubmit={save}><div className="form-grid"><label className="field"><span>Vendor Code *</span><input required value={form.code} onChange={e=>set("code",e.target.value)}/></label><label className="field"><span>Vendor Name *</span><input required value={form.name} onChange={e=>set("name",e.target.value)}/></label><label className="field"><span>Contact</span><input value={form.contact||""} onChange={e=>set("contact",e.target.value)}/></label><label className="field"><span>Phone</span><input value={form.phone||""} onChange={e=>set("phone",e.target.value)}/></label><label className="field"><span>Email</span><input value={form.email||""} onChange={e=>set("email",e.target.value)}/></label><label className="field"><span>Lead Time</span><div className="input-suffix"><input type="number" min="0" value={form.lead_time_days||0} onChange={e=>set("lead_time_days",e.target.value)}/><b>DAY</b></div></label><label className="field span2"><span>Remark</span><textarea rows="2" value={form.remark||""} onChange={e=>set("remark",e.target.value)}/></label></div><Alert>{error}</Alert><div className="modal-actions"><button type="button" className="btn ghost" onClick={onClose}>ยกเลิก</button><button className="btn primary" disabled={busy}>บันทึก</button></div></form></Modal>
}

export default function Vendors(){const auth=useAuth();const[rows,setRows]=useState([]);const[q,setQ]=useState("");const[error,setError]=useState("");const[modal,setModal]=useState(undefined);async function load(){try{const d=await apiGet("/suppliers/");setRows(d.results||[])}catch(err){setError(err.message)}}useEffect(()=>{load()},[]);const shown=useMemo(()=>rows.filter(x=>!q||`${x.code} ${x.name}`.toLowerCase().includes(q.toLowerCase())),[rows,q]);async function remove(x){if(!window.confirm(`ยืนยันลบ Vendor ${x.code}?`))return;try{await apiDelete(`/suppliers/${x.id}/`);load()}catch(err){setError(err.message)}}return <><PageHeader title="Vendor" subtitle="Vendor Master" actions={auth.can("can_manage_suppliers")&&<button className="btn primary" onClick={()=>setModal(null)}>+ เพิ่ม Vendor</button>}/><Alert>{error}</Alert><section className="panel"><div className="toolbar"><input className="search-input" value={q} onChange={e=>setQ(e.target.value)} placeholder="ค้นหา Vendor Code / Vendor Name..."/></div><div className="table-wrap"><table><thead><tr><th>Vendor Code</th><th>Vendor Name</th><th>Contact</th><th>Phone</th><th>Email</th><th>Lead Time</th><th>Status</th><th>Action</th></tr></thead><tbody>{shown.map(x=><tr key={x.id}><td><b>{x.code}</b></td><td>{x.name}</td><td>{x.contact||"-"}</td><td>{x.phone||"-"}</td><td>{x.email||"-"}</td><td>{x.lead_time_days} DAY</td><td><span className={`status ${x.active?"success":"muted"}`}>{x.active?"Active":"Inactive"}</span></td><td>{auth.can("can_manage_suppliers")&&<div className="row-actions"><button className="mini" onClick={()=>setModal(x)}>แก้ไข</button><button className="mini danger" onClick={()=>remove(x)}>ลบ</button></div>}</td></tr>)}</tbody></table></div></section>{modal!==undefined&&<VendorModal row={modal} onClose={()=>setModal(undefined)} onSaved={()=>{setModal(undefined);load()}}/>}</>}
