import { useEffect, useMemo, useState } from "react";
import { apiDelete, apiGet, apiPatch } from "../api";
import { useAuth } from "../auth";
import { Alert, Modal, PageHeader, fmt } from "../components/Common";

function EditHistory({ row, options, onClose, onSaved }) {
  const [quantity, setQuantity] = useState(row.quantity);
  const [machineId, setMachineId] = useState(row.machine ? (options.machines||[]).find(x=>x.code===row.machine)?.id||"" : "");
  const [requesterId, setRequesterId] = useState(row.requester_id||"");
  const [recorderId, setRecorderId] = useState(row.recorder_id||"");
  const [remark, setRemark] = useState(row.remark||"");
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  async function save(e){e.preventDefault();setBusy(true);setError("");try{await apiPatch(`/history/${row.id}/`,{quantity,machine_id:machineId,requester_id:requesterId,recorder_id:recorderId,remark});onSaved();}catch(err){setError(err.message)}finally{setBusy(false)}}
  return <Modal title="แก้ไขข้อมูล History" onClose={onClose}><form onSubmit={save}><div className="form-grid"><label className="field"><span>จำนวน *</span><input type="number" min="0.0001" step="any" value={quantity} onChange={e=>setQuantity(e.target.value)} required/></label><label className="field"><span>เครื่องจักร</span><select value={machineId} onChange={e=>setMachineId(e.target.value)}><option value="">-</option>{(options.machines||[]).map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></label><label className="field"><span>ผู้เบิก</span><select value={requesterId} onChange={e=>setRequesterId(e.target.value)}><option value="">-</option>{(options.employees||[]).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="field"><span>ผู้บันทึก</span><select value={recorderId} onChange={e=>setRecorderId(e.target.value)}><option value="">-</option>{(options.employees||[]).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="field span2"><span>Remark</span><textarea rows="3" value={remark} onChange={e=>setRemark(e.target.value)}/></label></div><Alert>{error}</Alert><div className="modal-actions"><button type="button" className="btn ghost" onClick={onClose}>ยกเลิก</button><button className="btn primary" disabled={busy}>บันทึก</button></div></form></Modal>
}

export default function History(){
  const auth=useAuth(); const [rows,setRows]=useState([]); const [options,setOptions]=useState({}); const [type,setType]=useState("ALL"); const [q,setQ]=useState(""); const [requester,setRequester]=useState(""); const [recorder,setRecorder]=useState(""); const [error,setError]=useState(""); const [edit,setEdit]=useState(null); const [loading,setLoading]=useState(true);
  async function load(){setLoading(true);setError("");try{const params=new URLSearchParams({type,q,requester_id:requester,recorder_id:recorder});const [h,o]=await Promise.all([apiGet(`/history/?${params}`),apiGet("/options/")]);setRows(h.results||[]);setOptions(o||{});}catch(err){setError(err.message)}finally{setLoading(false)}}
  useEffect(()=>{load()},[type,requester,recorder]);
  const shown=useMemo(()=>rows.filter(x=>!q||`${x.item_id} ${x.part_name} ${x.part_detail} ${x.maker} ${x.machine} ${x.requester} ${x.recorder}`.toLowerCase().includes(q.toLowerCase())),[rows,q]);
  async function remove(row){if(!window.confirm(`ยืนยันลบ/ยกเลิกรายการ ${row.item_id} ?\nระบบจะเก็บ Audit Log ไว้`))return;try{await apiDelete(`/history/${row.id}/delete/`);load()}catch(err){setError(err.message)}}
  return <><PageHeader title="ประวัติการเบิก / รับเข้า (History)" subtitle="Stock IN & Stock OUT พร้อมตัวกรองผู้เบิกและผู้บันทึก"/><Alert>{error}</Alert><section className="panel"><div className="tab-row"><button className={`tab ${type==="ALL"?"active":""}`} onClick={()=>setType("ALL")}>ทั้งหมด</button><button className={`tab ${type==="IN"?"active":""}`} onClick={()=>setType("IN")}>รับเข้า</button><button className={`tab ${type==="OUT"?"active":""}`} onClick={()=>setType("OUT")}>เบิกออก</button></div><div className="toolbar wrap"><input className="search-input" value={q} onChange={e=>setQ(e.target.value)} placeholder="ค้นหา Item ID / Part / Machine..."/><select value={requester} onChange={e=>setRequester(e.target.value)}><option value="">ผู้เบิกทั้งหมด</option>{(options.employees||[]).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select value={recorder} onChange={e=>setRecorder(e.target.value)}><option value="">ผู้บันทึกทั้งหมด</option>{(options.employees||[]).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><button className="btn ghost" onClick={load}>ค้นหา</button></div>{loading?<div className="empty">กำลังโหลด...</div>:<div className="table-wrap"><table><thead><tr><th>วันที่</th><th>เวลา</th><th>ประเภท</th><th>Item ID</th><th>Part Name</th><th>Part Detail</th><th>Maker</th><th>Location</th><th>เครื่องจักร</th><th>ชื่อผู้เบิก</th><th>ชื่อผู้บันทึก</th><th>จำนวน</th><th>Unit</th><th>Action</th></tr></thead><tbody>{shown.map(r=><tr key={r.id}><td>{r.date}</td><td>{r.time}</td><td><span className={`status ${r.type==="IN"?"success":"danger"}`}>{r.type==="IN"?"รับเข้า":r.type==="OUT"?"เบิกออก":"ปรับยอด"}</span></td><td><b>{r.item_id}</b></td><td>{r.part_name}</td><td className="detail-cell">{r.part_detail||"-"}</td><td>{r.maker||"-"}</td><td>{r.location||"-"}</td><td>{r.type==="OUT"?r.machine||"-":"-"}</td><td>{r.type==="OUT"?r.requester||"-":"-"}</td><td>{r.recorder||"-"}</td><td><b>{fmt(r.quantity)}</b></td><td>{r.unit}</td><td><div className="row-actions">{auth.can("can_edit_history")&&<button className="mini" onClick={()=>setEdit(r)}>แก้ไขข้อมูล</button>}{auth.can("can_delete_history")&&<button className="mini danger" onClick={()=>remove(r)}>ลบข้อมูล</button>}</div></td></tr>)}</tbody></table></div>}</section>{edit&&<EditHistory row={edit} options={options} onClose={()=>setEdit(null)} onSaved={()=>{setEdit(null);load()}}/>}</>
}
