# Generated by Django 5.2.17 on 2026-08-20 08:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MachineCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=100, unique=True)),
                (
                    "code_type",
                    models.CharField(
                        choices=[
                            ("CURRENT", "Current Code"),
                            ("OLD", "Old Code"),
                            ("ALIAS", "Alias"),
                            ("REFERENCE", "Reference"),
                        ],
                        default="REFERENCE",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "machine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codes",
                        to="core.machine",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
    ]
