# Generated by Django 5.2.17 on 2026-08-21 02:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_machinecode"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleAccess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("role_name", models.CharField(max_length=120, unique=True)),
                ("display_name", models.CharField(blank=True, max_length=120)),
                ("active", models.BooleanField(default=True)),
                ("can_view_dashboard", models.BooleanField(default=True)),
                ("can_view_parts", models.BooleanField(default=True)),
                ("can_edit_parts", models.BooleanField(default=False)),
                ("can_receive_stock", models.BooleanField(default=False)),
                ("can_issue_stock", models.BooleanField(default=False)),
                ("can_view_suppliers", models.BooleanField(default=False)),
                ("can_view_machines", models.BooleanField(default=False)),
                ("can_manage_roles", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["role_name"],
            },
        ),
    ]
