# Generated by Django 5.2.17 on 2026-08-21 16:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_roleaccess"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80, unique=True)),
                ("name", models.CharField(blank=True, max_length=120)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.AlterModelOptions(
            name="auditlog",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="machinecode",
            options={},
        ),
        migrations.AddField(
            model_name="auditlog",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to="core.employee",
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="dept_code",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="machine",
            name="work_code",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="machinecode",
            name="legacy_id",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="machinecode",
            name="legacy_source",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="roleaccess",
            name="can_add_employees",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="roleaccess",
            name="can_add_order",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="roleaccess",
            name="can_adjust_stock",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="roleaccess",
            name="can_cancel_order",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="roleaccess",
            name="can_delete_history",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="roleaccess",
            name="can_delete_order",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="roleaccess",
            name="can_edit_employees",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="roleaccess",
            name="can_edit_history",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="roleaccess",
            name="can_edit_order_info",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="roleaccess",
            name="can_edit_purchase_info",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="roleaccess",
            name="can_manage_machines",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="roleaccess",
            name="can_manage_order_projects",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="roleaccess",
            name="can_manage_suppliers",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="roleaccess",
            name="can_receive_order",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="roleaccess",
            name="can_update_edit_data",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="roleaccess",
            name="can_view_audit_log",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="roleaccess",
            name="can_view_employees",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="roleaccess",
            name="can_view_history",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="roleaccess",
            name="can_view_orders",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="roleaccess",
            name="can_view_safety_stock",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="is_void",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="recorded_by_employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recorded_stock_transactions",
                to="core.employee",
            ),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="voided_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stocktransaction",
            name="voided_by_employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="voided_stock_transactions",
                to="core.employee",
            ),
        ),
        migrations.AlterField(
            model_name="machinecode",
            name="code_type",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="machinecode",
            name="machine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="codes",
                to="core.machine",
            ),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("RECEIVE", "Receive"),
                    ("ISSUE", "Issue"),
                    ("ADJUSTMENT", "Adjustment"),
                    ("RETURN", "Return"),
                    ("TRANSFER_IN", "Transfer In"),
                    ("TRANSFER_OUT", "Transfer Out"),
                    ("IN", "Legacy In"),
                    ("OUT", "Legacy Out"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="OrderProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=250, unique=True)),
                ("description", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "created_by_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_order_projects",
                        to="core.employee",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("step_no", models.PositiveIntegerField()),
                ("import_filename", models.CharField(blank=True, max_length=255)),
                (
                    "imported_by_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="imported_order_steps",
                        to="core.employee",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="core.orderproject",
                    ),
                ),
            ],
            options={
                "ordering": ["project", "step_no"],
            },
        ),
        migrations.CreateModel(
            name="OrderRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("legacy_source", models.CharField(blank=True, max_length=80)),
                ("legacy_id", models.CharField(blank=True, max_length=120)),
                ("order_number", models.CharField(max_length=100, unique=True)),
                ("order_date", models.DateField()),
                ("factory", models.CharField(blank=True, max_length=30)),
                (
                    "group_order",
                    models.CharField(blank=True, db_index=True, max_length=250),
                ),
                ("job", models.CharField(blank=True, db_index=True, max_length=80)),
                ("urgent_status", models.CharField(blank=True, max_length=120)),
                ("pending_data_date", models.DateField(blank=True, null=True)),
                ("remark", models.TextField(blank=True)),
                ("quotation", models.TextField(blank=True)),
                ("part_name", models.CharField(max_length=300)),
                ("part_detail", models.TextField(blank=True)),
                ("maker_text", models.CharField(blank=True, max_length=250)),
                ("amount", models.PositiveIntegerField(default=1)),
                ("unit_text", models.CharField(max_length=80)),
                ("po_number", models.CharField(blank=True, max_length=120)),
                (
                    "price_per_unit",
                    models.DecimalField(decimal_places=4, default=0, max_digits=16),
                ),
                (
                    "price_total",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                ("lead_time_days", models.PositiveIntegerField(blank=True, null=True)),
                ("issue_pr_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("vendor_confirm_date", models.DateField(blank=True, null=True)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(db_index=True, default="New Order", max_length=80),
                ),
                ("cancel_status", models.BooleanField(db_index=True, default=False)),
                (
                    "edit_data_status",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("edit_workflow_enabled", models.BooleanField(default=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[("NORMAL", "Normal"), ("PROJECT", "Project")],
                        db_index=True,
                        default="NORMAL",
                        max_length=20,
                    ),
                ),
                (
                    "usage_status",
                    models.CharField(
                        choices=[("USED", "ใช้"), ("NOT_USED", "ไม่ได้ใช้")],
                        default="USED",
                        max_length=20,
                    ),
                ),
                ("stock_received", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deleted_by_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_order_records",
                        to="core.employee",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_records",
                        to="core.machine",
                    ),
                ),
                (
                    "ordered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_order_records",
                        to="core.employee",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_records",
                        to="core.part",
                    ),
                ),
                (
                    "person_in_charge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_order_records",
                        to="core.employee",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="core.orderproject",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_order_records",
                        to="core.employee",
                    ),
                ),
                (
                    "stock_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_orders",
                        to="core.stocktransaction",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_records",
                        to="core.supplier",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="core.orderstep",
                    ),
                ),
            ],
            options={
                "ordering": ["-order_date", "-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="orderstep",
            constraint=models.UniqueConstraint(
                fields=("project", "step_no"), name="uniq_project_step"
            ),
        ),
    ]
