# Generated by Django 5.2.17 on 2026-08-31 09:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_order_visibility_and_date_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="email",
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
        migrations.CreateModel(
            name="IntegrationCredential",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(max_length=30, unique=True)),
                ("encrypted_credentials", models.TextField(blank=True)),
                ("account_email", models.EmailField(blank=True, max_length=254)),
                ("scopes", models.JSONField(blank=True, default=list)),
                ("connected_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("pending_state_hash", models.CharField(blank=True, db_index=True, max_length=64)),
                ("pending_code_verifier", models.TextField(blank=True)),
                ("pending_at", models.DateTimeField(blank=True, null=True)),
                (
                    "connected_by_employee",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="connected_integrations", to="core.employee"),
                ),
                (
                    "pending_by_employee",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="pending_integrations", to="core.employee"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderRFQ",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rfq_number", models.CharField(max_length=80, unique=True)),
                ("group_order", models.CharField(db_index=True, max_length=250)),
                ("job", models.CharField(db_index=True, max_length=80)),
                ("vendor_name", models.CharField(blank=True, max_length=250)),
                ("recipient_email", models.EmailField(db_index=True, max_length=254)),
                ("sender_email", models.EmailField(blank=True, max_length=254)),
                ("requested_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("SENT", "Sent"), ("FAILED", "Failed"), ("CANCELLED", "Cancelled")], db_index=True, default="DRAFT", max_length=20)),
                ("subject", models.CharField(blank=True, max_length=500)),
                ("body_text", models.TextField(blank=True)),
                ("to_emails", models.JSONField(blank=True, default=list)),
                ("cc_emails", models.JSONField(blank=True, default=list)),
                ("gmail_message_id", models.CharField(blank=True, max_length=200)),
                ("gmail_thread_id", models.CharField(blank=True, db_index=True, max_length=200)),
                ("rfc_message_id", models.CharField(blank=True, db_index=True, max_length=500)),
                ("gmail_web_link", models.TextField(blank=True)),
                ("send_error", models.TextField(blank=True)),
                (
                    "sent_by_employee",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sent_order_rfqs", to="core.employee"),
                ),
                (
                    "vendor",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="order_rfqs", to="core.supplier"),
                ),
            ],
            options={"ordering": ["-requested_at", "-created_at"]},
        ),
        migrations.CreateModel(
            name="OrderRFQItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order_number", models.CharField(max_length=100)),
                ("item_id", models.CharField(blank=True, max_length=100)),
                ("part_name", models.CharField(max_length=300)),
                ("part_detail", models.TextField(blank=True)),
                ("amount", models.PositiveIntegerField(default=1)),
                ("unit", models.CharField(max_length=80)),
                ("order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="rfq_items", to="core.orderrecord")),
                ("rfq", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="core.orderrfq")),
            ],
            options={"ordering": ["created_at"]},
        ),
        migrations.CreateModel(
            name="POBalance",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quotation_received_at", models.DateTimeField(blank=True, null=True)),
                ("price", models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ("currency", models.CharField(default="THB", max_length=10)),
                ("lead_time_days", models.PositiveIntegerField(blank=True, null=True)),
                ("vendor_delivery_date", models.DateField(blank=True, null=True)),
                ("actual_delivery_date", models.DateField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                ("rfq", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="po_balance", to="core.orderrfq")),
                ("updated_by_employee", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="updated_po_balances", to="core.employee")),
            ],
            options={"ordering": ["-updated_at"]},
        ),
        migrations.CreateModel(
            name="RFQCCRule",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rule_type", models.CharField(choices=[("DEFAULT", "ทุกการส่ง"), ("JOB", "ตาม JOB")], db_index=True, max_length=20)),
                ("job", models.CharField(blank=True, db_index=True, max_length=80)),
                ("email", models.EmailField(max_length=254)),
                ("display_name", models.CharField(blank=True, max_length=200)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("created_by_employee", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_rfq_cc_rules", to="core.employee")),
            ],
            options={"ordering": ["rule_type", "job", "email"]},
        ),
        migrations.CreateModel(
            name="RFQMessage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("message_type", models.CharField(choices=[("RFQ_REQUEST", "ขอราคา"), ("PRICE_FOLLOW_UP", "ตามราคา"), ("DELIVERY_FOLLOW_UP", "ตามวันที่จัดส่ง"), ("VENDOR_REPLY", "Vendor ตอบกลับ")], max_length=30)),
                ("direction", models.CharField(choices=[("OUTBOUND", "Outbound"), ("INBOUND", "Inbound")], max_length=10)),
                ("status", models.CharField(choices=[("PENDING", "Pending"), ("SENT", "Sent"), ("RECEIVED", "Received"), ("FAILED", "Failed")], default="PENDING", max_length=20)),
                ("subject", models.CharField(blank=True, max_length=500)),
                ("body_text", models.TextField(blank=True)),
                ("from_email", models.EmailField(blank=True, max_length=254)),
                ("to_emails", models.JSONField(blank=True, default=list)),
                ("cc_emails", models.JSONField(blank=True, default=list)),
                ("gmail_message_id", models.CharField(blank=True, db_index=True, max_length=200)),
                ("gmail_thread_id", models.CharField(blank=True, db_index=True, max_length=200)),
                ("rfc_message_id", models.CharField(blank=True, db_index=True, max_length=500)),
                ("gmail_web_link", models.TextField(blank=True)),
                ("occurred_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("error", models.TextField(blank=True)),
                ("rfq", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="core.orderrfq")),
                ("sent_by_employee", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sent_rfq_messages", to="core.employee")),
            ],
            options={"ordering": ["occurred_at", "created_at"]},
        ),
        migrations.CreateModel(
            name="RFQAttachment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("filename", models.CharField(max_length=500)),
                ("mime_type", models.CharField(blank=True, max_length=200)),
                ("size", models.PositiveBigIntegerField(default=0)),
                ("gmail_attachment_id", models.CharField(blank=True, max_length=500)),
                ("gmail_message_id", models.CharField(blank=True, max_length=200)),
                ("quotation_revision", models.PositiveIntegerField(default=0)),
                ("message", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="core.rfqmessage")),
            ],
            options={"ordering": ["created_at"]},
        ),
        migrations.CreateModel(
            name="VendorEmailIdentity",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("vendor_name", models.CharField(blank=True, max_length=250)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("confirmed_by_employee", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="confirmed_vendor_email_identities", to="core.employee")),
                ("vendor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="email_identities", to="core.supplier")),
            ],
            options={"ordering": ["email"]},
        ),
        migrations.AddIndex(
            model_name="orderrfq",
            index=models.Index(fields=["group_order", "job"], name="core_orderr_group_o_f9f996_idx"),
        ),
        migrations.AddIndex(
            model_name="orderrfq",
            index=models.Index(fields=["status", "requested_at"], name="core_orderr_status_e08672_idx"),
        ),
        migrations.AddConstraint(
            model_name="orderrfqitem",
            constraint=models.UniqueConstraint(fields=("rfq", "order"), name="uniq_order_rfq_item"),
        ),
        migrations.AddConstraint(
            model_name="rfqccrule",
            constraint=models.UniqueConstraint(fields=("rule_type", "job", "email"), name="uniq_rfq_cc_rule"),
        ),
        migrations.AddConstraint(
            model_name="rfqmessage",
            constraint=models.UniqueConstraint(condition=models.Q(("gmail_message_id", ""), _negated=True), fields=("rfq", "gmail_message_id"), name="uniq_rfq_gmail_message"),
        ),
    ]
